# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: DojoIO
subtitle: elevate your skills〔´∇｀〕
email: buivd4@hotmail.com
title_separator: "|"
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to DojoIO, your premier destination for top-notch training in AWS cloud services, 
  including comprehensive courses, hands-on playgrounds, and challenging mock tests designed to 
  help you master cloud computing. 
  Dive into our ChatGPT training courses to unlock the potential of AI in your projects. 
  Explore our extensive online book readers, offering a rich library of resources to supplement your learning. 
  Whether you're an aspiring cloud professional or an experienced developer, DojoIO has the tools and expertise to elevate your skills to new heights.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dojo.io.vn" # the base hostname & protocol for your site, e.g. http://example.com
repository: nothing-fancy/dojo.io.vn
github_username:  buivd4

socials:
  github: https://github.com/buivd4
  linked_in: https://linked.in/in/buivd4
  email: buivd4@hotmail.com

atom_feed:
  hide: true
# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# minimal-mistakes-jekyll settings
minimal_mistakes_skin: mint

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "single"
      author_profile: true


author:
  name: "Dương"
  avatar: "/assets/img/bio-photo.jpg"
  bio: ">Tầm nhìn ta thật ngắn mà đã thấy bao thứ để làm — Alan Turing"
  links:
    - label: "DojoIO"
      icon: "fas fa-fw fa-link"
      url: "https://dojo.io.vn"
    - label: "buivd4"
      icon: "fab fa-linkedin-in"
      url: "https://linked.in/in/buivd4"
    - label: "buivd4"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/buivd4"